namespace BotReport2026.Writers;

/// <summary>
/// The VBA embedded in DS_SAE.xlsm. The export button lives in the workbook rather
/// than in this app because staff finish the EDD columns in Excel — exporting from
/// there means they never have to come back to the generator.
///
/// Two VBA traps this code has already been bitten by, so keep them in mind when
/// editing: identifiers are <b>case-insensitive</b>, so a local named `csvPath`
/// and a function named `CsvPath()` are the same name and fail to compile; and
/// nothing here is compiled by the build, so a mistake only surfaces when someone
/// clicks the button in Excel.
///
/// Deliberately ASCII-only: VBA module source is stored in the project's code page,
/// so Thai literals here would not survive round-tripping. Thai belongs in the
/// worksheet and on the button caption, which are XML and safe. For the same reason
/// the "other reason" case is detected by the helper cell being non-empty rather
/// than by matching the Thai dropdown text.
/// </summary>
public static class SaeVbaMacro
{
    public const string ModuleName = "BotReportExport";
    public const string EntryPoint = "ExportToCsv";

    /// <param name="sheetName">Worksheet holding the data.</param>
    /// <param name="headerRow">1-based row of the field-name header.</param>
    /// <param name="totalColumns">Columns on the sheet, including the 7.1 helper.</param>
    /// <param name="otherColumn">1-based column of the 7.1 helper, dropped on export.</param>
    public static string Build(string sheetName, int headerRow, int totalColumns, int otherColumn) => $@"Option Explicit

' Generated by BotReport2026 - do not edit by hand.
' Exports this sheet to the .csv accepted by the BoT Data Acquisition System.

Private Const SHEET_NAME As String = ""{sheetName}""
Private Const HEADER_ROW As Long = {headerRow}
Private Const TOTAL_COLS As Long = {totalColumns}
Private Const OTHER_COL As Long = {otherColumn}   ' field 7.1 - folded into field 7
Private Const RESULT_COL As Long = 6
Private Const REASON_COL As Long = 7
Private Const AMOUNT_COL As Long = 13

Public Sub {EntryPoint}()
    Dim ws As Worksheet
    Dim lastRow As Long, r As Long, c As Long
    Dim parts() As String, idx As Long
    Dim lines() As String, lineCount As Long
    Dim outPath As String

    On Error GoTo Failed

    Set ws = ThisWorkbook.Worksheets(SHEET_NAME)
    lastRow = ws.Cells(ws.Rows.Count, 1).End(xlUp).Row
    If lastRow <= HEADER_ROW Then
        MsgBox ""Nothing to export."", vbExclamation
        Exit Sub
    End If

    ' Data rows only - the submission .csv carries no header row.
    ReDim lines(0 To lastRow - HEADER_ROW - 1)
    lineCount = 0

    Application.ScreenUpdating = False

    For r = HEADER_ROW + 1 To lastRow
        ReDim parts(0 To TOTAL_COLS - 2)   ' one column is dropped
        idx = 0
        For c = 1 To TOTAL_COLS
            If c <> OTHER_COL Then
                parts(idx) = Escape(FieldText(ws, r, c))
                idx = idx + 1
            End If
        Next c
        lines(lineCount) = Join(parts, ""|"")
        lineCount = lineCount + 1
    Next r

    outPath = TargetCsvPath()
    WriteUtf8 outPath, Join(lines, vbCrLf) & vbCrLf

    Application.ScreenUpdating = True
    MsgBox ""Exported "" & (lastRow - HEADER_ROW) & "" rows to:"" & vbCrLf & outPath, _
           vbInformation, ""DS_SAE""
    Exit Sub

Failed:
    Application.ScreenUpdating = True
    MsgBox ""Export failed: "" & Err.Description, vbCritical, ""DS_SAE""
End Sub

' Value for one cell, with the transformations the spec requires on export.
Private Function FieldText(ws As Worksheet, ByVal r As Long, ByVal c As Long) As String
    Dim v As Variant

    v = ws.Cells(r, c).Value

    Select Case c
        Case RESULT_COL
            ' The dropdown shows ""0 = ..."" but the spec wants Char(1).
            FieldText = Left$(Trim$(v & """"), 1)
        Case REASON_COL
            ' A non-empty 7.1 helper means the user picked the free-text option.
            If Trim$(ws.Cells(r, OTHER_COL).Value & """") <> """" Then
                FieldText = Trim$(ws.Cells(r, OTHER_COL).Value & """")
            Else
                FieldText = Trim$(v & """")
            End If
        Case 5, 9, 10
            FieldText = DateText(v)
        Case AMOUNT_COL
            FieldText = AmountText(v)
        Case Else
            FieldText = Trim$(v & """")
    End Select
End Function

' Always YYYY-MM-DD. Year/Month/Day are used instead of Format(d, ""yyyy-mm-dd"")
' because a Buddhist-era regional setting would otherwise emit 2569 for 2026.
Private Function DateText(ByVal v As Variant) As String
    Dim d As Date
    Dim s As String

    If IsEmpty(v) Or IsNull(v) Then
        DateText = """"
        Exit Function
    End If

    If VarType(v) = vbDate Then
        d = CDate(v)
    Else
        s = Trim$(CStr(v))
        If s = """" Then
            DateText = """"
            Exit Function
        End If
        ' Already normalised by the generator - pass through untouched.
        If Len(s) = 10 Then
            If Mid$(s, 5, 1) = ""-"" And Mid$(s, 8, 1) = ""-"" Then
                DateText = s
                Exit Function
            End If
        End If
        If Not IsDate(s) Then
            DateText = s
            Exit Function
        End If
        d = CDate(s)
    End If

    DateText = Format$(Year(d), ""0000"") & ""-"" & _
               Format$(Month(d), ""00"") & ""-"" & Format$(Day(d), ""00"")
End Function

' Raw number, no thousands separator - the field is Number(20,2).
Private Function AmountText(ByVal v As Variant) As String
    Dim s As String
    If IsEmpty(v) Or IsNull(v) Then
        AmountText = """"
    ElseIf IsNumeric(v) Then
        s = Format$(CDbl(v), ""0.00"")
        ' Guard against a locale that uses comma as the decimal separator.
        If InStr(s, "","") > 0 Then s = Replace(s, "","", ""."")
        AmountText = s
    Else
        AmountText = Trim$(CStr(v))
    End If
End Function

' Every field is wrapped in double quotes, unconditionally, and the fields are
' joined with a pipe. Embedded quotes are doubled, as in RFC 4180.
Private Function Escape(ByVal v As String) As String
    Escape = """""""" & Replace(v, """""""", """""""""""") & """"""""
End Function

Private Function TargetCsvPath() As String
    Dim n As String
    n = ThisWorkbook.FullName
    If InStrRev(n, ""."") > 0 Then n = Left$(n, InStrRev(n, ""."") - 1)
    TargetCsvPath = n & "".csv""
End Function

' UTF-8 *with* BOM. Without the BOM Excel on a Thai Windows reads the file back as
' CP874 and every Thai character is mangled; UTF-8 consumers ignore the BOM.
Private Sub WriteUtf8(ByVal filePath As String, ByVal content As String)
    Dim stream As Object
    Set stream = CreateObject(""ADODB.Stream"")
    stream.Type = 2
    stream.Charset = ""utf-8""
    stream.Open
    stream.WriteText content
    stream.SaveToFile filePath, 2      ' adSaveCreateOverWrite
    stream.Close
End Sub
";
}
